vehicle_model:
  simple_bicycle_model:
  # some made up values
    kinematics:
      lr: 0.72
      lf: 0.72
      sf: 1.15
      sr: 1.15
    tire:
      Blat: 11.63
      Clat: -1.38
      Dlat: 1.6
      Elat: 1.0
    aero:
      cla: 3.7
      cda: 1.1
      aeroArea: 1.1
    m: 178.0
    Izz: 111.0
    wheelRadius: 0.206
    gearRatio: 12.23
    innerSteeringRatio: 0.255625
    outerSteeringRatio: 0.20375
    nominalVoltageTS: 550.0
    powerGroundForce: 700.0
    powertrainEfficiency: 0.95

  fssim_model:
    inertia:
      m:        190.0   # Weight of the Vehicle [kg]
      m_driver: 0.0     # Weight of the driver  [kg]
      g:        9.81    # Graviti force         [m/s^2]
      I_z:      110    # Inertial force I_zz 

    kinematics:
      l: 1.53           # Vehicle Length [m]
      b_F: 1.22          # From COG to front axle [m]
      b_R: 1.22         # From COG to rear axle [m]
      w_front: 0.5    # Percentage of weight front
      h_cg: 0.262       # Heights of COG [m]

      # l_F = l * (1 - w_front);  # Front cg lever arm [m]
      # l_R = l * w_front;  # Rear  cg lever arm [m]

    # Magic Formula:
    # y=D*sin(C*atan(B*(1-E)*x+E*atan(B*x)))
    tire:
      tire_coefficient: 1.0
      B: 12.56
      C: -1.38
      D: 1.60
      E: -0.58

    aero:
      C_Down: # F_Downforce = C_Downforce*v_x^2; C_Downforce = a*b*c
        a: 1.22
        b: 2.6
        c: 0.6
      C_drag: # F_Drag = C_Drag*v_x^2; C_drag = a*b*c
        a: 0.7
        b: 1.0
        c: 1.0

    drivetrain:
      Cm1: 5000
      Cr0: 180
      inertia: 0.4 # wheel_plus_packaging
      r_dyn: 0.231
      nm_wheels: 4